version: '3.8'

services:
  my-app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - mongo # link to mongodb

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb-db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  mongodb-db:

      